### ISSUE TITLE
ODE's computation

### ISSUE THREAD

**Issue by arthurserres** [facebookresearch/SymbolicMathematics#18]
Hello, 

First of all thanks for your work and to share it ! 

I was wondering if there is a notebook about how to use the ODE's prediction instead of the integral prediction and if not where can I find instruction about how to do so ?

Thanks by advance :) 

Best, 

Arthur SERRES
student in applied mathematics.

**Comment by ebotiab** [comment]
Hello @arthurserres, I have searched for this also and I have realised how it can be done. You can find my implementation in my forked repository: https://github.com/ebotiab/SymbolicMathematics (the ODE' prediction can be found at the end of the Research_Project file)

**Comment by arthurserres** [comment]
I have just seen your answer. Thank you very much @ebotiab, this is very helpful. I will definitely quote you in my project :) 

Good continuity and thanks again for your work
